config/routes.rb
Rails.application.routes.draw do
  resources :usuarios do
    member do
      get :siguiendo, :seguidores
    end
  end
  resources :sesiones, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relacions, only: [:create, :destroy]

  root  'paginas_estaticas#home'

  match '/alta',     to: 'usuarios#new',              via: 'get'
  match '/ayuda',    to: 'paginas_estaticas#help',    via: 'get'
  match '/acerca',   to: 'paginas_estaticas#about',   via: 'get'
  match '/contacto', to: 'paginas_estaticas#contact', via: 'get'
  match '/ingreso',  to: 'sesiones#new',              via: 'get'
  match '/salida',   to: 'sesiones#destroy',          via: 'delete'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      El formulario contiene <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.usuario), feed_item.usuario %>
  <span class="usuario">
    <%= link_to feed_item.usuario.nombre, feed_item.usuario %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.usuario) %>
    <%= link_to "borrar", feed_item, method: :delete,
                                     data: { confirm: "¿Estas seguro?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_formulario_micropost.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
	<div class="field">
	  <%= f.text_area :content,class: "form-control", placeholder: "Escribe un nuevo micropost..." %>
	</div>
	<%= f.submit "Publicar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_info_usuario.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.nombre %>
</h1>
<span>
  <%= link_to "ver mi perfil", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/shared/_stats.html.erb
<% @usuario ||= current_user %>
<div class="stats">
  <a href="<%= siguiendo_usuario_path(@usuario) %>">
    <strong id="siguiendo" class="stat">
      <%= @usuario.usuarios_seguido.count %>
    </strong>
    siguiendo
  </a>
  <a href="<%= seguidores_usuario_path(@usuario) %>">
    <strong id="seguidores" class="stat">
      <%= @usuario.seguidores.count %>
    </strong>
    seguidores
  </a>
</div>