config/routes.rb
Rails.application.routes.draw do
  resources :usuarios do
    member do
      get :siguiendo, :seguidores
    end
  end
  resources :sesiones, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relacions, only: [:create, :destroy]

  root  'paginas_estaticas#home'

  match '/alta',     to: 'usuarios#new',              via: 'get'
  match '/ayuda',    to: 'paginas_estaticas#help',    via: 'get'
  match '/acerca',   to: 'paginas_estaticas#about',   via: 'get'
  match '/contacto', to: 'paginas_estaticas#contact', via: 'get'
  match '/ingreso',  to: 'sesiones#new',              via: 'get'
  match '/salida',   to: 'sesiones#destroy',          via: 'delete'

end

app/views/layouts/_cabecera.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-default">
  <div class="container"><%= link_to "Aplicacion de Ejemplo", root_path, id: "logo" %>
	<nav>
	  <ul class="nav pull-right navbar-nav">
	    <li><%= link_to "Inicio", root_path %></li>
	    <li><%= link_to "Ayuda", ayuda_path %></li>
	    <% if signed_in? %>
	      <li><%= link_to "Usuarios", usuarios_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Cuenta <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Herramientas", edit_usuario_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Salir", salida_path, method: "delete" %>
                </li>
              </ul>
            </li>
	    <% else %>
	      <li><%= link_to "Ingresar", ingreso_path %></li>
	    <% end %>
	  </ul>
	</nav>
  </div>
</header>

app/views/layouts/_pie.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Tutorial de Rails</a>
    por Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca",   acerca_path %></li>
      <li><%= link_to "Contacto", contacto_path %></li>
      <li><a href="http://news.railstutorial.org/">Novedades</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_titulo(yield(:titulo)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/cabecera' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/pie' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>