config/routes.rb
Rails.application.routes.draw do
  resources :usuarios do
    member do
      get :siguiendo, :seguidores
    end
  end
  resources :sesiones, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relacions, only: [:create, :destroy]

  root  'paginas_estaticas#home'

  match '/alta',     to: 'usuarios#new',              via: 'get'
  match '/ayuda',    to: 'paginas_estaticas#help',    via: 'get'
  match '/acerca',   to: 'paginas_estaticas#about',   via: 'get'
  match '/contacto', to: 'paginas_estaticas#contact', via: 'get'
  match '/ingreso',  to: 'sesiones#new',              via: 'get'
  match '/salida',   to: 'sesiones#destroy',          via: 'delete'

end

app/controllers/paginas_estaticas_controller.rb
class PaginasEstaticasController < ApplicationController
  def home
  	if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/paginas_estaticas_helper.rb
module PaginasEstaticasHelper
end

app/views/paginas_estaticas/about.html.erb
<% provide(:titulo, 'Nosotros') %>
<h1>Acerca de Nosotros</h1>
<p>
El <a href="http://railstutorial.org/">Tutorial de Ruby y Rails</a> es un proyecto para hacer un libro y pantallazos para enseñar desarrollo web con <a href="http://rubyonrails.org/"> Ruby y Rails</a>. Este es un ejemplo por el Tutorial.
</p>

app/views/paginas_estaticas/contact.html.erb
<% provide(:titulo, 'Contacto') %>
<h1>Contacto</h1>
<p>
Contacta Ruby y Rails Tutorial acerca de este ejemplo en la <a href="http://railstutorial.org/contact">Pagina de Contacto</a>.
</p>

app/views/paginas_estaticas/help.html.erb
<% provide(:titulo, 'Ayuda') %>
<h1>Ayuda</h1>
<p>Obten ayuda sobre Ruby y Rails aqui <a href="http://railstutorial.org/help"> Pagina de Ayuda de Rails Tutorial</a>.
Para obtener ayuda sobre este ejemplo, mira aqui <a href="http://railstutorial.org/book">Libro Tutorial de Rails</a>.</p>

app/views/paginas_estaticas/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="col-lg-4">
      <section>
        <%= render 'shared/info_usuario' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/formulario_micropost' %>
      </section>
    </aside>
    <div class="col-lg-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
	<div class="center jumbotron">
		<h1>Bienvenido a la Aplicacion de ejemplo</h1>
		<h2>
			Esto es la pagina de inicio para el
			<a href="http://railstutorial.org/">Tutorial Ruby y Rails</a>
			Aplicacion de ejemplo
		</h2>
		<%= link_to "Registrate Ahora!", alta_path, class: "btn btn-large btn-primary" %>
	</div>

	<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>